### ISSUE TITLE
Support of CocoaPods

### ISSUE THREAD

**Issue by thomalexandre** [makleso6/NukeWebP#2]
It would be great to have the plugin available via CocoaPods

**Comment by makleso6** [comment]
Hi @thomalexandre I try to add it)

**Comment by makleso6** [comment]
Oh, https://github.com/kean/Nuke does not support cocoapods(

**Comment by thomalexandre** [comment]
Of course it does support -> https://cocoapods.org/pods/Nuke

**Comment by makleso6** [comment]
latest version in cococapods is [10.7.1](https://github.com/CocoaPods/Specs/tree/master/Specs/3/d/e/Nuke/10.7.1)
but latest version in repo 11.3.0 (https://github.com/kean/Nuke/releases/tag/11.3.0)

**Comment by thomalexandre** [comment]
it's fine, it could be already good
