### ISSUE TITLE
Bump to NukeV12

### ISSUE THREAD

**Issue by pm-dev** [makleso6/NukeWebP#5]
Thoughts on bumping the dependency on nuke to v12?

**Comment by makleso6** [comment]
check latest release

**Comment by pm-dev** [comment]
🙌 thx. It looks like libwebp's latest version is also 1.3.2 (fixed some security issues). After updating that on my fork I was still able to build and the functionality I use still works as expected.

**Comment by makleso6** [comment]
update to latest version
